mode = 'Regression'  # {Scratch, Regression, Transfer, PU_learning, PU_predict}
file1 = 'datasets/regression/Hexo_min.csv' # 'datasets/regrepositive_smiles.csv'
file2 = 'datasets/unlabeled_smiles.csv'
variable1 = 'SMILES'
variable2 = 'SMILES'
target = 'dH_exo (kJ/mol)'#'label'
fptype = 'Mordred'  #{'Mordred','ECFP','Avalon','ErG','RDKit','MACCSKeys','Estate'}
model_path = 'PU_models/*.pkl'
lr = 0.001   # only Transfer
epochs = 200
number = 5